### ISSUE TITLE
Coregistration in spm: Other Images

### ISSUE THREAD

**Issue by GMerakis** [andrewjahn/AndysBrainBook#37]
In https://andysbrainbook.readthedocs.io/en/latest/SPM/SPM_Short_Course/SPM_04_Preprocessing/03_SPM_Coregistration.html

You mentioned that source will be moved around,
The other images are the ones that would be aligned with the source.
But it's not mentioned in the doc.

If we use say mean img as reference, how can we align the other functional images?

I know if I use anat as reference, I can move all func images to coregister to the anat image

**Comment by NickGuAI** [comment]
Sorry just realized how this works. Also this is my alt account..

To anyone who come across this:

The coregistration step used anatomical image as source (i.e move around),
then performed segmentation on the coregistered image.

This means two things:

1. The anatomical image is already moved around to match the reference image
2. The segmentation on coregistered image means we normalize previous images (realign, slice-timing) images to the fitted anatomical image.

Since during segmentation, the anatomical image was segmented based on MNI space unless otherwise specified, the functional would be normalized to MNI space when using the generated image.

That being said, when analyzing data in this case, since the functional images were not moved around, wouldn't the images/brain still be distorted? I.E If we perform per-voxel cluster analysis, would coregistered all functional images to anatomical be better then what we do now?

**Comment by andrewjahn** [comment]
Hi there,

Yes, it's true that any coregistration or normalization will introduce some interpolations and distortions; the reason for using the mean functional as the reference image is to reduce the number of interpolations to the functional data during preprocessing, and also to save disk space - if the functional images are realigned to the anatomical image, they will also be resampled to match its resolution, which in most cases is 1x1x1 or less. This can lead to huge output files, and there could be a lot of information lost during resampling that severe. Basically, you have to choose one as the reference or the other, and I believe that using the mean functional image leads to fewer problems.


Best,

-Andy
