### ISSUE TITLE
Asking for the sample data in the f-ASL tutorial

### ISSUE THREAD

**Issue by Guobwen** [andrewjahn/AndysBrainBook#38]
Hi Andy,
      I'm studying to analyze ASL data using the f-ASL toolbox these days, following your tutorial of the website https://andysbrainbook.readthedocs.io/en/latest/ASL/04_fASL_GUI.html.  However, I cannot find the link of the sample data of the N-back experiment you mentioned, would you be kind enough to provide us with the sample data?    
     Another question is that if I want to use the f-ASL toolbox to analyze data in my study, which paper should I cite?

      Best wishes!

**Comment by andrewjahn** [comment]
Hi there,

Apologies for the very late reply! The ASL tutorial hasn't been updated in a while since I'm helping Luis Hernandez-Garcia, the original developer of fASL, to create a series of educational materials on how to use that software package. Unfortunately I don't have access to the N-back experiment, and I'm not sure whether I'll complete the ASL tutorial on the e-book.


Best,

-Andy
